name: build workflow

on:
  push: 
    branches:
      - main

jobs:
  build-action:
    needs: test-action
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repo
        uses: actions/checkout@v7
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
    
