name: first workflow

on:
  push: 
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repo
        uses: actions/checkout@v7
        
      - name: Test
        run: dotnet test ./LearningGithubActions.slnx --filter Shard=${{ matrix.shards }}
    
